<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Force full width content layout
// add_filter( 'genesis_site_layout', '__genesis_return_full_width_content' );

remove_action('genesis_loop', 'genesis_do_loop');

remove_action('genesis_sidebar', 'genesis_do_sidebar');
add_action('genesis_sidebar', 'custom_sidebar'); // Add custom sidebar

add_action('genesis_loop', 'custom_entry_content'); // Add custom loop
add_action('genesis_after_content_sidebar_wrap', 'custom_genesis_after_entry'); // Add custom loop
add_action('genesis_after_header', 'genesischild_top_wrap_widgets');

global $post;
function genesischild_top_wrap_widgets()
{
    $hero_url = get_the_post_thumbnail_url(get_the_ID(), 'full_hd');
    $background_mobile = get_field('background_mobile', get_the_ID());
    ?>
    <section class="banner banner-single-post <?php echo (empty($hero_url)) ? 'empty' : null ?>">

        <div class="banner__rotate bg-cover white" data-mobile="<?php echo $background_mobile ?>"
             style="background-image: url(<?php echo $hero_url ?>);">

            <?php if (!empty($background_mobile)): ?>
                <style>
                    @media screen and (max-width: 960px) {
                        .banner__rotate {
                            background-image: url(<?php echo $background_mobile ?>) !important;
                        }
                </style>
            <?php endif; ?>

            <div class="banner__content">

                <h1 class="banner__title"><?php the_title() ?></h1>

                <?php if ($link = get_field('contact_link')): ?>
                    <div class="button__container">
                        <a class="button button--tranperent" href="<?php echo $link['url']; ?>"
                           target="<?php if ($link['target']) {
                               echo $link['target'];
                           } else {
                               echo '_parent';
                           } ?>"><?php echo $link['title']; ?></a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </section>
<?php }

function custom_genesis_after_entry()
{
    if (have_rows('attorneys_boxes')): ?>
        <div class="attorney-info">
            <?php while (have_rows('attorneys_boxes')): the_row();
                $attorney_name = get_sub_field('attorney_name');
                $shortened_description = get_sub_field('shortened_description');
                $attorney_position = get_sub_field('position');
                $attorney_image = get_sub_field('attorney_image');
                if ($attorney_name && $shortened_description) : ?>
                    <div class="attorney-info__item">
                        <div class="attorney-info__col">
                            <div class="attorney-info__heading">
                                <?php echo _e('Presented By', 'von-hacht-associates'); ?>
                            </div>
                            <?php if ($attorney_position): ?>
                                <div class="attorney-info__position">
                                    <?php echo esc_html($attorney_position); ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($attorney_name): ?>
                                <div class="attorney-info__name">
                                    <?php echo esc_html($attorney_name); ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($attorney_image): ?>
                                <div class="attorney-info__image">
                                    <?php echo wp_get_attachment_image($attorney_image['id'], 'large'); ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="attorney-info__col">
                            <?php if ($shortened_description): ?>
                                <div class="attorney-info__description">
                                    <?php echo $shortened_description; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php
                endif;
            endwhile; ?>
        </div>
    <?php endif;
}

function custom_entry_content()
{ ?>
    <div id="main_container">
        <div class="default-page-container">
            <div class="grid-container">
                <div class="grid-x grid-margin-x list-decor">
                    <div class="cell">
                        <?php get_template_part('parts/core/breadcrumbs', null); ?>
                    </div>
                    <?php if (have_posts()) : ?>
                        <?php while (have_posts()) : the_post(); ?>
                            <div class="cell">
                                <?php add_filter('the_content', 'wpautop'); ?>
                                <?php the_content(); ?>
                            </div>
                        <?php endwhile; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php }

function custom_sidebar()
{
    if ($seminar_sidebar_form = get_field('seminar_sidebar_form')) :
        ?>
        <div class="sidebar-form" id="footer-form">
            <?php echo $seminar_sidebar_form ?>
        </div>
    <?php
    elseif ($sidebar_form = get_field('sidebar_form', 'options')) : ?>
        <div class="sidebar-form" id="footer-form">
            <?php echo $sidebar_form; ?>
        </div>
    <?php endif; ?>
    <?php if ($sidebar_testimonial_show = get_field('sidebar_testimonial_show', 'options')): ?>
    <div class="sidebar-testimonial">
        <?php if ($testimonials_heading = get_field('sidebar_testimonial_heading', 'options')): ?>
            <h2 class="sidebar-testimonial__heading"><?php echo $testimonials_heading ?></h2>
        <?php endif; ?>
        <?php foreach ($sidebar_testimonial_show as $post):
            setup_postdata($post); ?>
            <div class="sidebar-testimonial__text">
                <?php echo mb_strimwidth(get_the_content(), 0, 300, '...');
                ?>
            </div>
        <?php endforeach; ?>
        <?php if ($testimonials_all_link = get_field('testimonials_all_link', 'options')): ?>
            <div class="sidebar-testimonial__all text-center">
                <a class="button" href="<?php echo $testimonials_all_link['url']; ?>"
                   target="<?php $testimonials_all_link['target'] ?: '_self'; ?>"><?php echo $testimonials_all_link['title']; ?></a>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>

    <?php

    $override_sidebar = get_field('override_default_services');

    if( $override_sidebar ) {
        
        if( have_rows('manual_related_services') ) : ?>
            <div class="areas-list">
                <div class="areas-list__container">
                    <h2 class="areas-list__parent">Services</h2>
                    <ul class="areas-list__children">
                        <?php while( have_rows('manual_related_services') ) : the_row(); 
                            $service_page_id = get_sub_field('service');
                            $page_title = get_field('title_in_the_sidebar', $service_page_id);
                            $page_url = get_permalink($service_page_id);
                        ?>
                            <li class="areas-list__child <?php echo ($service_page_id == get_the_ID()) ? ' areas-list__child-active' : '' ?>">
                                <a href="<?php echo $page_url; ?>"
                                class="areas-list__link"><span><?php echo $page_title ? $page_title : get_the_title($service_page_id) ?></span></a>
                            </li>
                        <?php endwhile; ?>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
    <?php } else {
        $current_page_id = get_the_ID();
        $parent_page = wp_get_post_parent_id($current_page_id);
        if ($parent_page):
            $parent_title = get_the_title($parent_page);
            ?>
            <?php
            $args = array(
                'post_type' => 'page',
                'post_parent' => $parent_page,
                'posts_per_page' => -1,
            );
            $child_pages = new WP_Query($args);
            if ($child_pages->have_posts()) :?>
                <div class="areas-list">
                    <div class="areas-list__container">
                        <h2 class="areas-list__parent"><?php echo $parent_title ?></h2>
                        <ul class="areas-list__children">

                            <?php while ($child_pages->have_posts()) :
                                $child_pages->the_post();
                                $changed_title = get_field('title_in_the_sidebar');
                                ?>
                                <li class="areas-list__child<?php echo ($current_page_id == get_the_ID()) ? ' areas-list__child-active' : '' ?>">
                                    <a href="<?php echo get_the_permalink(); ?>"
                                    class="areas-list__link"><span><?php echo $changed_title ?: get_the_title(); ?></span></a>
                                </li>
                            <?php endwhile;
                            wp_reset_postdata(); ?>
                        </ul>
                    </div>
                </div>
            <?php endif;
        endif; 
    }
}
genesis(); ?>
