<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
remove_action('genesis_loop', 'genesis_do_loop');
add_action('genesis_loop', 'custom_entry_content'); // Add custom loop
add_action('genesis_after_header', 'genesischild_top_wrap_widgets');

function genesischild_top_wrap_widgets()
{
    $hero_url = get_the_post_thumbnail_url(get_the_ID(), 'full_hd'); ?>
    <section class="banner banner-staff">


        <?php if (get_field('mobile_image')): ?>

            <div class="banner__rotate bg-cover white show-for-small-only"
                 style="background-image: url(<?php echo get_field('mobile_image')['url'] ?>);">
                <div class="banner__content">

                    <h1 class="banner__title"><?php the_title() ?></h1>

                    <?php if ($item2 = get_field('position')): ?>
                        <h3><?php echo $item2 ?></h3>
                    <?php endif; ?>
                    <?php if ($link = get_field('contact_link')): ?>
                        <div class="button__container">
                            <a class="button button--tranperent" href="<?php echo $link['url']; ?>"
                               target="<?php if ($link['target']) {
                                   echo $link['target'];
                               } else {
                                   echo '_parent';
                               } ?>"><?php echo $link['title']; ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="banner__rotate bg-cover white hide-for-small-only"
                 style="background-image: url(<?php echo $hero_url ?>);">
                <div class="banner__content">

                    <h1 class="banner__title"><?php the_title() ?></h1>

                    <?php if ($item2 = get_field('position')): ?>
                        <h3><?php echo $item2 ?></h3>
                    <?php endif; ?>
                    <?php if ($link = get_field('contact_link')): ?>
                        <div class="button__container">
                            <a class="button button--tranperent" href="<?php echo $link['url']; ?>"
                               target="<?php if ($link['target']) {
                                   echo $link['target'];
                               } else {
                                   echo '_parent';
                               } ?>"><?php echo $link['title']; ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

        <?php else: ?>

            <div class="banner__rotate bg-cover white" style="background-image: url(<?php echo $hero_url ?>);">
                <div class="banner__content">

                    <h1 class="banner__title"><?php the_title() ?></h1>

                    <?php if ($item2 = get_field('position')): ?>
                        <h3><?php echo $item2 ?></h3>
                    <?php endif; ?>
                    <?php if ($link = get_field('contact_link')): ?>
                        <div class="button__container">
                            <a class="button button--tranperent" href="<?php echo $link['url']; ?>"
                               target="<?php if ($link['target']) {
                                   echo $link['target'];
                               } else {
                                   echo '_parent';
                               } ?>"><?php echo $link['title']; ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

        <?php endif; ?>

    </section>

<?php }

function custom_entry_content()
{ ?>

    <div id="main_container" class="post-about-us">

        <div class="default-post-container">

            <?php if (have_rows('tabs')): ?>
                <section class="team-tab">
                    <div class="grid-container">
                        <div class="grid-x grid-margin-x">
                            <div class="cell">
                                <?php get_template_part('parts/core/breadcrumbs', null); ?>
                            </div>
                            <div class="cell">
                                <ul class="team-tab-list">
                                    <?php
                                    $i = 1;
                                    while (have_rows('tabs')): the_row();
                                        $title = get_sub_field('tab_name') ? get_sub_field('tab_name') : 'Tab-' . $i; ?>
                                        <li class="team-tab-li <?php if ($i == '1') {
                                            echo 'open';
                                        } ?>" data-tab-id="team-tab-id-<?php echo $i; ?>"><?php echo $title ?></li>
                                        <?php $i++; endwhile; ?>
                                </ul>
                                <?php
                                $i = 1;
                                while (have_rows('tabs')): the_row();
                                    $content = get_sub_field('content'); ?>
                                    <div class="team-tab-content list-decor team-tab-id-<?php echo $i; ?> <?php if ($i == '1') {
                                        echo 'open';
                                    } ?>">
                                        <?php echo $content ?>
                                    </div>
                                    <?php $i++; endwhile; ?>
                            </div>
                        </div>
                    </div>
                </section>
            <?php endif; ?>


        </div>
    </div>
<?php }

genesis();
?>
